import type { User, Job, Review } from "./types";

export const seedUsers: User[] = [
  {
    id: "u_demo_client",
    name: "Sample Client",
    email: "client@hirewave.ng",
    password: "hirewave1",
    role: "client",
    avatarSeed: "sampleClient",
    location: "Lagos, Nigeria",
    joinedAt: "2024-02-11",
  },
  {
    id: "u_demo_free",
    name: "Sample Freelancer",
    email: "freelancer@hirewave.ng",
    password: "hirewave1",
    role: "freelancer",
    title: "Senior Full-Stack Engineer",
    bio: "I help Nigerian startups ship reliable, beautiful product. 8 years building React, Node, and Postgres apps.",
    hourlyRate: 25000,
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "Paystack"],
    avatarSeed: "sampleFree",
    location: "Yaba, Lagos",
    joinedAt: "2023-08-04",
  },
  {
    id: "u_f1",
    name: "Adaeze Okeke",
    email: "adaeze@hirewave.ng",
    password: "hirewave1",
    role: "freelancer",
    title: "Product Designer · Design Systems",
    bio: "Crafting design systems for fintech and B2B SaaS across Lagos and Nairobi. Previously at Flutterwave.",
    hourlyRate: 30000,
    skills: ["Figma", "Design Systems", "Webflow", "Prototyping", "UX Research"],
    avatarSeed: "adaeze",
    location: "Lekki, Lagos",
    joinedAt: "2022-04-12",
  },
  {
    id: "u_f2",
    name: "Ibrahim Bello",
    email: "ibrahim@hirewave.ng",
    password: "hirewave1",
    role: "freelancer",
    title: "ML Engineer · LLM Apps",
    bio: "Shipping production LLM agents, RAG pipelines, and evaluation harnesses for African fintechs.",
    hourlyRate: 40000,
    skills: ["Python", "LangChain", "PyTorch", "Pinecone", "FastAPI"],
    avatarSeed: "ibrahim",
    location: "Abuja, Nigeria",
    joinedAt: "2021-11-30",
  },
  {
    id: "u_f3",
    name: "Chiamaka Eze",
    email: "chiamaka@hirewave.ng",
    password: "hirewave1",
    role: "freelancer",
    title: "Brand & Motion Designer",
    bio: "Editorial-grade brand systems, launch films, and product motion for fast-growing African startups.",
    hourlyRate: 22000,
    skills: ["After Effects", "Cinema 4D", "Brand Identity", "Illustration"],
    avatarSeed: "chiamaka",
    location: "Enugu, Nigeria",
    joinedAt: "2023-01-19",
  },
  {
    id: "u_f4",
    name: "Tunde Adebayo",
    email: "tunde@hirewave.ng",
    password: "hirewave1",
    role: "freelancer",
    title: "DevOps & Platform Engineer",
    bio: "Kubernetes, Terraform, and zero-downtime deploys. I make platforms boring (in a good way).",
    hourlyRate: 28000,
    skills: ["Kubernetes", "Terraform", "AWS", "Go", "Observability"],
    avatarSeed: "tunde",
    location: "Ibadan, Nigeria",
    joinedAt: "2020-09-02",
  },
  {
    id: "u_f5",
    name: "Ngozi Umeh",
    email: "ngozi@hirewave.ng",
    password: "hirewave1",
    role: "freelancer",
    title: "Mobile Engineer · iOS / Android",
    bio: "Native and React Native specialist. Shipped 20+ apps used across Nigeria and Ghana.",
    hourlyRate: 26000,
    skills: ["Swift", "Kotlin", "React Native", "Expo", "GraphQL"],
    avatarSeed: "ngozi",
    location: "Port Harcourt, Nigeria",
    joinedAt: "2022-06-22",
  },
  {
    id: "u_c1",
    name: "Paystack Africa",
    email: "hiring@paystackafrica.ng",
    password: "hirewave1",
    role: "client",
    avatarSeed: "paystackafrica",
    location: "Victoria Island, Lagos",
    joinedAt: "2023-03-04",
  },
  {
    id: "u_c2",
    name: "Kano Tech Studio",
    email: "team@kanotech.ng",
    password: "hirewave1",
    role: "client",
    avatarSeed: "kanotech",
    location: "Kano, Nigeria",
    joinedAt: "2023-11-09",
  },
];

export const seedJobs: Job[] = [
  {
    id: "j1",
    clientId: "u_c1",
    clientName: "Paystack Africa",
    title: "Next.js dashboard for merchant payouts (real-time)",
    description:
      "We need a senior React engineer to build a real-time merchant payout dashboard. Stack: Next.js 15, tRPC, Tailwind, and a websocket layer over our Go backend. You'll own component architecture and data fetching patterns.",
    category: "Web Development",
    skills: ["Next.js", "TypeScript", "Tailwind", "WebSockets", "tRPC"],
    budgetMin: 1800000,
    budgetMax: 3500000,
    paymentType: "fixed",
    experience: "expert",
    duration: "1-3m",
    verified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    proposalsCount: 14,
  },
  {
    id: "j2",
    clientId: "u_c2",
    clientName: "Kano Tech Studio",
    title: "Design system overhaul for analytics suite",
    description:
      "Audit our existing Figma library and propose a v2 design system. Token architecture, component primitives, accessibility audits, and a Storybook documentation pass with our engineering team.",
    category: "Design",
    skills: ["Figma", "Design Systems", "Storybook", "Accessibility"],
    budgetMin: 20000,
    budgetMax: 35000,
    paymentType: "hourly",
    experience: "expert",
    duration: "3-6m",
    verified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    proposalsCount: 9,
  },
  {
    id: "j3",
    clientId: "u_c1",
    clientName: "Paystack Africa",
    title: "LLM-powered support agent with retrieval pipeline",
    description:
      "Build a production-grade support agent over our docs. Embeddings + hybrid retrieval, evaluation harness, guardrails, and a small admin UI to manage prompts and review traces.",
    category: "AI / ML",
    skills: ["Python", "LangChain", "Pinecone", "FastAPI", "Evaluation"],
    budgetMin: 2500000,
    budgetMax: 4500000,
    paymentType: "fixed",
    experience: "expert",
    duration: "1-3m",
    verified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    proposalsCount: 22,
  },
  {
    id: "j4",
    clientId: "u_c2",
    clientName: "Kano Tech Studio",
    title: "Marketing site rebuild in Astro + Tailwind",
    description:
      "Rebuild our marketing site for performance and editorial polish. ~12 pages, MDX-driven blog, smooth scroll transitions, and a CMS integration with Sanity.",
    category: "Web Development",
    skills: ["Astro", "Tailwind", "Sanity", "MDX"],
    budgetMin: 1200000,
    budgetMax: 2200000,
    paymentType: "fixed",
    experience: "intermediate",
    duration: "1-3m",
    verified: false,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 90).toISOString(),
    proposalsCount: 31,
  },
  {
    id: "j5",
    clientId: "u_c1",
    clientName: "Paystack Africa",
    title: "Kubernetes platform hardening & cost audit",
    description:
      "Review our EKS clusters, propose multi-tenant isolation, set up Karpenter, and deliver a cost & reliability report with quick wins implemented.",
    category: "DevOps",
    skills: ["Kubernetes", "AWS", "Terraform", "Karpenter"],
    budgetMin: 25000,
    budgetMax: 45000,
    paymentType: "hourly",
    experience: "expert",
    duration: "less-1m",
    verified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    proposalsCount: 6,
  },
  {
    id: "j6",
    clientId: "u_c2",
    clientName: "Kano Tech Studio",
    title: "React Native app for habit tracking (v1 launch)",
    description:
      "Greenfield React Native app, Expo Router, offline-first with WatermelonDB, and Google Fit / Apple Health integrations. Launch v1 on iOS and Android.",
    category: "Mobile",
    skills: ["React Native", "Expo", "TypeScript", "WatermelonDB"],
    budgetMin: 2800000,
    budgetMax: 5500000,
    paymentType: "fixed",
    experience: "expert",
    duration: "3-6m",
    verified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
    proposalsCount: 17,
  },
];

export const seedReviews: Review[] = [
  {
    id: "r1",
    freelancerId: "u_demo_free",
    clientName: "Paystack Africa",
    jobTitle: "Internal admin tool rebuild",
    rating: 5,
    comment: "Shipped ahead of schedule. Communication and code quality were both exceptional.",
    date: "2025-02-18",
  },
  {
    id: "r2",
    freelancerId: "u_demo_free",
    clientName: "Kano Tech Studio",
    jobTitle: "Customer portal v2",
    rating: 5,
    comment: "Easily one of the best engineers we've worked with on the marketplace.",
    date: "2024-11-02",
  },
  {
    id: "r3",
    freelancerId: "u_f1",
    clientName: "Flutterwave",
    jobTitle: "Design system tokens",
    rating: 5,
    comment: "Adaeze brought rigor and taste. She levelled up our entire design org.",
    date: "2025-01-10",
  },
  {
    id: "r4",
    freelancerId: "u_f2",
    clientName: "Helix AI Lagos",
    jobTitle: "RAG pipeline + eval harness",
    rating: 5,
    comment: "Ibrahim is the rare ML engineer who actually ships production software.",
    date: "2024-12-19",
  },
];

export const categories = [
  { name: "Web Development", icon: "Code2", count: 1284 },
  { name: "Design", icon: "Palette", count: 842 },
  { name: "AI / ML", icon: "Sparkles", count: 412 },
  { name: "Mobile", icon: "Smartphone", count: 526 },
  { name: "DevOps", icon: "Server", count: 318 },
  { name: "Writing", icon: "PenLine", count: 671 },
  { name: "Marketing", icon: "Megaphone", count: 489 },
  { name: "Data", icon: "Database", count: 357 },
];
