import type { User, Job, Review } from "./types";

export const seedUsers: User[] = [
  {
    id: "u_demo_client",
    name: "Demo Client",
    email: "client@demo.com",
    password: "demo1234",
    role: "client",
    avatarSeed: "demoClient",
    location: "San Francisco, USA",
    joinedAt: "2024-02-11",
  },
  {
    id: "u_demo_free",
    name: "Demo Freelancer",
    email: "freelancer@demo.com",
    password: "demo1234",
    role: "freelancer",
    title: "Senior Full-Stack Engineer",
    bio: "I help startups ship reliable, beautiful product. 8 years building React, Node, and edge-native backends.",
    hourlyRate: 95,
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS"],
    avatarSeed: "demoFree",
    location: "Lisbon, Portugal",
    joinedAt: "2023-08-04",
  },
  {
    id: "u_f1",
    name: "Amara Okafor",
    email: "amara@hire.dev",
    password: "demo1234",
    role: "freelancer",
    title: "Product Designer · Design Systems",
    bio: "Crafting design systems for fintech and B2B SaaS. Previously at Linear and Vercel.",
    hourlyRate: 120,
    skills: ["Figma", "Design Systems", "Webflow", "Prototyping", "UX Research"],
    avatarSeed: "amara",
    location: "Berlin, Germany",
    joinedAt: "2022-04-12",
  },
  {
    id: "u_f2",
    name: "Hiroshi Tanaka",
    email: "hiroshi@hire.dev",
    password: "demo1234",
    role: "freelancer",
    title: "ML Engineer · LLM Apps",
    bio: "Shipping production LLM agents, RAG pipelines, and evaluation harnesses.",
    hourlyRate: 145,
    skills: ["Python", "LangChain", "PyTorch", "Pinecone", "FastAPI"],
    avatarSeed: "hiroshi",
    location: "Tokyo, Japan",
    joinedAt: "2021-11-30",
  },
  {
    id: "u_f3",
    name: "Sofía Martín",
    email: "sofia@hire.dev",
    password: "demo1234",
    role: "freelancer",
    title: "Brand & Motion Designer",
    bio: "Editorial-grade brand systems, launch films, and product motion for venture-backed startups.",
    hourlyRate: 90,
    skills: ["After Effects", "Cinema 4D", "Brand Identity", "Illustration"],
    avatarSeed: "sofia",
    location: "Barcelona, Spain",
    joinedAt: "2023-01-19",
  },
  {
    id: "u_f4",
    name: "Daniel Weiss",
    email: "daniel@hire.dev",
    password: "demo1234",
    role: "freelancer",
    title: "DevOps & Platform Engineer",
    bio: "Kubernetes, Terraform, and zero-downtime deploys. I make platforms boring (in a good way).",
    hourlyRate: 110,
    skills: ["Kubernetes", "Terraform", "AWS", "Go", "Observability"],
    avatarSeed: "daniel",
    location: "Toronto, Canada",
    joinedAt: "2020-09-02",
  },
  {
    id: "u_f5",
    name: "Priya Raman",
    email: "priya@hire.dev",
    password: "demo1234",
    role: "freelancer",
    title: "Mobile Engineer · iOS / Android",
    bio: "Native and React Native specialist. Shipped 30+ apps with millions of downloads.",
    hourlyRate: 100,
    skills: ["Swift", "Kotlin", "React Native", "Expo", "GraphQL"],
    avatarSeed: "priya",
    location: "Bangalore, India",
    joinedAt: "2022-06-22",
  },
  {
    id: "u_c1",
    name: "Atlas Robotics",
    email: "hiring@atlas.co",
    password: "demo1234",
    role: "client",
    avatarSeed: "atlas",
    location: "Boston, USA",
    joinedAt: "2023-03-04",
  },
  {
    id: "u_c2",
    name: "Northwind Studio",
    email: "team@northwind.studio",
    password: "demo1234",
    role: "client",
    avatarSeed: "northwind",
    location: "Stockholm, Sweden",
    joinedAt: "2023-11-09",
  },
];

export const seedJobs: Job[] = [
  {
    id: "j1",
    clientId: "u_c1",
    clientName: "Atlas Robotics",
    title: "Next.js dashboard for fleet telemetry (real-time)",
    description:
      "We need a senior React engineer to architect a real-time fleet telemetry dashboard. Stack: Next.js 15, tRPC, Tailwind, and a websocket layer over our Rust backend. You'll own component architecture, data fetching patterns, and a small design system extension.",
    category: "Web Development",
    skills: ["Next.js", "TypeScript", "Tailwind", "WebSockets", "tRPC"],
    budgetMin: 6000,
    budgetMax: 12000,
    paymentType: "fixed",
    experience: "expert",
    duration: "1-3m",
    verified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    proposalsCount: 14,
  },
  {
    id: "j2",
    clientId: "u_c2",
    clientName: "Northwind Studio",
    title: "Design system overhaul for B2B analytics suite",
    description:
      "Audit our existing Figma library and propose a v2 design system. Token architecture, component primitives, accessibility audits, and a Storybook documentation pass with our engineering team.",
    category: "Design",
    skills: ["Figma", "Design Systems", "Storybook", "Accessibility"],
    budgetMin: 80,
    budgetMax: 130,
    paymentType: "hourly",
    experience: "expert",
    duration: "3-6m",
    verified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    proposalsCount: 9,
  },
  {
    id: "j3",
    clientId: "u_c1",
    clientName: "Atlas Robotics",
    title: "LLM-powered support agent with retrieval pipeline",
    description:
      "Build a production-grade support agent over our docs. Embeddings + hybrid retrieval, evaluation harness, guardrails, and a small admin UI to manage prompts and review traces.",
    category: "AI / ML",
    skills: ["Python", "LangChain", "Pinecone", "FastAPI", "Evaluation"],
    budgetMin: 8000,
    budgetMax: 15000,
    paymentType: "fixed",
    experience: "expert",
    duration: "1-3m",
    verified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    proposalsCount: 22,
  },
  {
    id: "j4",
    clientId: "u_c2",
    clientName: "Northwind Studio",
    title: "Marketing site rebuild in Astro + Tailwind",
    description:
      "Rebuild our marketing site for performance and editorial polish. ~12 pages, MDX-driven blog, smooth scroll transitions, and a CMS integration with Sanity.",
    category: "Web Development",
    skills: ["Astro", "Tailwind", "Sanity", "MDX"],
    budgetMin: 4000,
    budgetMax: 7000,
    paymentType: "fixed",
    experience: "intermediate",
    duration: "1-3m",
    verified: false,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 90).toISOString(),
    proposalsCount: 31,
  },
  {
    id: "j5",
    clientId: "u_c1",
    clientName: "Atlas Robotics",
    title: "Kubernetes platform hardening & cost audit",
    description:
      "Review our EKS clusters, propose multi-tenant isolation, set up Karpenter, and deliver a cost & reliability report with quick wins implemented.",
    category: "DevOps",
    skills: ["Kubernetes", "AWS", "Terraform", "Karpenter"],
    budgetMin: 100,
    budgetMax: 160,
    paymentType: "hourly",
    experience: "expert",
    duration: "less-1m",
    verified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    proposalsCount: 6,
  },
  {
    id: "j6",
    clientId: "u_c2",
    clientName: "Northwind Studio",
    title: "React Native app for habit tracking (v1 launch)",
    description:
      "Greenfield React Native app, Expo Router, offline-first with WatermelonDB, and Apple Health integrations. Launch v1 on iOS and Android.",
    category: "Mobile",
    skills: ["React Native", "Expo", "TypeScript", "WatermelonDB"],
    budgetMin: 9000,
    budgetMax: 18000,
    paymentType: "fixed",
    experience: "expert",
    duration: "3-6m",
    verified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
    proposalsCount: 17,
  },
];

export const seedReviews: Review[] = [
  {
    id: "r1",
    freelancerId: "u_demo_free",
    clientName: "Atlas Robotics",
    jobTitle: "Internal admin tool rebuild",
    rating: 5,
    comment: "Shipped ahead of schedule. Communication and code quality were both exceptional.",
    date: "2025-02-18",
  },
  {
    id: "r2",
    freelancerId: "u_demo_free",
    clientName: "Northwind Studio",
    jobTitle: "Customer portal v2",
    rating: 5,
    comment: "Easily the best engineer we've worked with on the marketplace.",
    date: "2024-11-02",
  },
  {
    id: "r3",
    freelancerId: "u_f1",
    clientName: "Linear-ish Inc",
    jobTitle: "Design system tokens",
    rating: 5,
    comment: "Amara brought rigor and taste. She levelled up our entire design org.",
    date: "2025-01-10",
  },
  {
    id: "r4",
    freelancerId: "u_f2",
    clientName: "Helix AI",
    jobTitle: "RAG pipeline + eval harness",
    rating: 5,
    comment: "Hiroshi is the rare ML engineer who actually ships production software.",
    date: "2024-12-19",
  },
];

export const categories = [
  { name: "Web Development", icon: "Code2", count: 1284 },
  { name: "Design", icon: "Palette", count: 842 },
  { name: "AI / ML", icon: "Sparkles", count: 412 },
  { name: "Mobile", icon: "Smartphone", count: 526 },
  { name: "DevOps", icon: "Server", count: 318 },
  { name: "Writing", icon: "PenLine", count: 671 },
  { name: "Marketing", icon: "Megaphone", count: 489 },
  { name: "Data", icon: "Database", count: 357 },
];
