[build]
  command = "npm run build"
  functions = ".netlify/functions"
  publish = ".output/public"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
